export const leadForm = [
  {
    label: "Company Name",
    name: "company_name",
    type: "select",
    required: true,
  },
  {
    label: "Contact Person",
    name: "contact_person",
    type: "select",
    required: true,
  },
  {
    label: "Mobile No",
    name: "mobile_no",
    type: "number",
    required: true,
  },
  {
    label: "Group Name",
    name: "group_name",
    type: "text",
    required: false,
  },
  {
    label: "Add Group",
    name: "add_group",
    type: "text",
    required: false,
  },
  {
    label: "Branch / Div",
    name: "branch_div",
    type: "text",
    required: false,
  },
  {
    label: "GST Number",
    name: "gst_number",
    type: "text",
    required: false,
  },
  {
    label: "Nature of Biz",
    name: "nature_of_biz",
    type: "text",
    required: false,
  },
  {
    label: "Email ID",
    name: "email",
    type: "email",
    required: false,
  },
  {
    label: "Website",
    name: "website",
    type: "text",
    required: false,
  },
  {
    label: "Address Line 1",
    name: "address_line_1",
    type: "text",
    required: true,
  },
  {
    label: "Address Line 2",
    name: "address_line_2",
    type: "text",
    required: false,
  },
  {
    label: "Address Line 3",
    name: "address_line_3",
    type: "text",
    required: false,
  },
  {
    label: "Address Line 4",
    name: "address_line_4",
    type: "text",
    required: false,
  },
  {
    label: "Country",
    name: "country",
    type: "select",
    required: true,
    options: ["India"],
  },
  {
    label: "State",
    name: "state",
    type: "select",
    required: true,
    // options: ["Tamil Nadu", "Kerala", "Karnataka"],
  },
  {
    label: "Pincode",
    name: "pincode",
    type: "number",
    required: true,
  },
  {
    label: "Company Details",
    name: "company_details",
    type: "textarea",
    required: true,
    rows: 4,
  },
];
